version: '2'
services:
  redis:
    restart: always
    build:
      context: ./dck_file
      dockerfile: redis_dck
    image: redis_img
    container_name: redis_cnt
    privileged: true
    ports:
      - "6379:6379"
    command: redis-server /usr/local/redis/redis.conf

 



